services:
  api:
    build: 
      context: .
      dockerfile: ./infra/api/dev/Dockerfile.dev
    volumes:
      - ./api:/var/www/html


  app:
    build: 
      context: .
      dockerfile: ./infra/app/dev/Dockerfile.dev
    ports:
      - 3000:3000
      - 6006:6006
    tty: true
    stdin_open: true
    volumes:
      - ./app:/home/node/shomotsu

  web:
    build: 
      context: .
      dockerfile: ./infra/web/dev/Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - ./api:/var/www/html
      
  storage:
    build: 
      context: .
      dockerfile: ./infra/storage/Dockerfile
    ports:
      - 9020:9020
      - 9090:9090
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9090" /data --address :9020
    volumes:
      - ./infra/storage/.minio/data:/data
    
  redis:
    build: 
      context: .
      dockerfile: ./infra/redis/Dockerfile
    ports:
      - 6379:6379
    volumes:
      - ./infra/redis/data:/data
      - ./infra/redis/redis.conf:/etc/redis.conf