FROM node:22.11.0-bullseye

USER root

RUN npm i -g npm@latest vercel@latest npm-check-updates
RUN apt-get update && apt-get -y install vim git

COPY ./app /home/node/shomotsu
RUN chown -R node:node /home/node/shomotsu

RUN groupmod -g 1000 node && usermod -u 1000 -g 1000 node
USER node

WORKDIR /home/node/shomotsu