name: Setup terraform
description: terraform composite action

inputs:
  working-directory:
    description: working directory
    required: false
    default: "./infra/dev"
  region:
    description: "aws region"
    required: false
    default: "ap-northeast-1"
  accept:
    description: "terraform accept"
    required: false
    default: "no"
  terraform_tfstate_key:
    description: "tfstate key"
    required: true
    default: ""
  terraform_tfstate_s3_bucket:
    description: "s3 bucket for tfstate"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3

    # - name: tflint
    #   working-directory: ${{ inputs.working-directory }}
    #   continue-on-error: true

    - name: fmt
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: true
      run: |
        terraform fmt -check -diff 2>&1

    - name: init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: true
      run: |
        terraform init \
          -migrate-state \
          -backend-config="bucket=${{ env.BUCKET_NAME }}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=ap-northeast-1"

    - name: validate
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: true
      run: |
        terraform validate -no-color 2>&1

    - name: plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: true
      run: |
        terraform plan -no-color -detailed-exitcode -input=false 2>&1
    # 
    # - name: apply
    #   shell: bash
    #   working-directory: ${{ inputs.working-directory }}
    #   continue-on-error: true