name: Setup terraform
description: terraform composite action

inputs:
  working-directory:
    description: working directory
    required: false
    default: "terraform/dev"
  region:
    description: "aws region"
    required: false
    default: "ap-northeast-1"
  apply:
    description: "terraform apply"
    required: false
    default: "no"
  terraform_tfstate_key:
    description: "tfstate key"
    required: true
    default: ""
  terraform_tfstate_s3_bucket:
    description: "s3 bucket for tfstate"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3

    # - name: tflint
    #   working-directory: ${{ inputs.working-directory }}
    #   continue-on-error: true

    - name: fmt
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: true
      run: |
        terraform fmt -check -diff

    - name: init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: true
      run: |
        terraform init \
          -migrate-state \
          -backend-config="bucket=${{ inputs.terraform_tfstate_s3_bucket }}" \
          -backend-config="key=${{ inputs.terraform_tfstate_key }}" \
          -backend-config="region=${{ inputs.region }}"

    - name: validate
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: true
      run: |
        terraform validate -no-color

    - name: plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: true
      run: |
        terraform plan -no-color -detailed-exitcode -input=false
    
    - name: apply
      if: ${{ inputs.apply == 'yes' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: true
      run: terraform apply -no-color -input=false -auto-approve