name: Code check

on: 
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  
permissions:
  id-token: write
  contents: read
  
jobs:
  setup:
    runs-on: ubuntu-latest          
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: actions/setup-node@v4

  front:
    name: Front
    needs: 
      - setup
    runs-on: ubuntu-latest
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build container 
        run: |
          mkdir -p app/node_modules
          chmod 777 app/node_modules
          sudo chown -R 1000:1000 app
          docker compose -f docker-compose.lint.yml up -d app
          
      - name: Run npm ci
        run: |
          echo "::notice title=npm ci"
          echo "::group::npm ci"
          docker compose run --rm --user 1000:1000 app npm ci
          echo "::endgroup::"

      - name: Run npm run lint
        run: |
          echo "::notice title=npm run lint"
          echo "::group::npm run lint"
          docker compose run --rm --user 1000:1000 app npm run lint
          echo "::endgroup::"

      - name: Run npm run test
        run: |
          echo "::notice title=npm run test"
          echo "::group::npm run test"
          docker compose run --rm --user 1000:1000 app npm run test:r
          echo "::endgroup::"

  api:
    name: API
    needs: 
      - setup
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: "password"
      AWS_DEFAULT_REGION: us-east-1
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build container 
        run: |
          docker compose -f docker-compose.lint.yml up -d api web storage redis

      - name: Setup Laravel
        run: |
          echo "::notice title=setup laravel"
          echo "::group::setup laravel"
          docker compose -f docker-compose.lint.yml run --rm --user root api php -r "file_exists('.env') || copy('.env.testing', '.env');"
          docker compose -f docker-compose.lint.yml run --rm --user 1000:1000 api composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          docker compose -f docker-compose.lint.yml run --rm --user 1000:1000 api composer require brianium/paratest --dev
          docker compose -f docker-compose.lint.yml run --rm --user 1000:1000 api php artisan key:generate --env=testing
          docker compose -f docker-compose.lint.yml run --rm --user 1000:1000 api chmod -R 777 storage bootstrap/cache
          docker compose -f docker-compose.lint.yml run --rm --user 1000:1000 api touch database/database.sqlite
          docker compose -f docker-compose.lint.yml run --rm --user 1000:1000 api php artisan config:clear
          docker compose -f docker-compose.lint.yml run --rm --user 1000:1000 api php artisan cache:clear
          echo "::endgroup::"

      - name: Configure MinIO in .env
        run: |
          echo "AWS_ACCESS_KEY_ID=root" >> .env
          echo "AWS_SECRET_ACCESS_KEY=password" >> .env
          echo "AWS_DEFAULT_REGION=ap-northeast-1" >> .env
          echo "AWS_BUCKET=test-bucket" >> .env
          echo "AWS_ENDPOINT=http://localhost:9020" >> .env
          echo "AWS_USE_PATH_STYLE_ENDPOINT=true" >> .env
          
      - name: Run pint
        run: |
          echo "::notice title=pint"
          echo "::group::pint"
          docker compose -f docker-compose.lint.yml run --rm --user 1000:1000 api ./vendor/bin/pint
          echo "::endgroup::"

      - name: Run phpunit
        env:
          DB_CONNECTION: sqlite
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: /var/www/html/database/database.sqlite
        run: |
          echo "::notice title=php artisan phpunit"
          echo "::group::php artisan phpunit"
          docker compose -f docker-compose.lint.yml run --rm --user 1000:1000 api php artisan test --parallel --processes=4
          echo "::endgroup::"
  
  result:
    needs: [front,api]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check Status
        run: |
          if [ "${{ contains(needs.*.result, 'failure') }}" = "true" ]; then
            echo "Failed"
            exit 1
          else
            echo "Success"
          fi