name: Destroy terraform

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  
env:
  AWS_REGION : "ap-northeast-1"
  ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_ARN }}
  TERRAFORM_TFSTATE_KEY: ${{ secrets.TERRAFORM_TFSTATE_KEY }}
  TERRAFORM_TFSTATE_S3_BUCKET: ${{ secrets.TERRAFORM_TFSTATE_S3_BUCKET }}

jobs:
  destory:
    runs-on: ubuntu-latest    
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - uses: ./.github/actions/terraform/destroy
        with:
          apply: "yes"
          region: ${{ env.AWS_REGION }}
          terraform_tfstate_key: ${{ env.TERRAFORM_TFSTATE_KEY }}
          terraform_tfstate_s3_bucket: ${{ env.TERRAFORM_TFSTATE_S3_BUCKET }}